import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

async function main() {
  const dir = path.dirname(fileURLToPath(import.meta.url));
  const txtPath = path.join(dir, 'shakespeare.txt');
  const outPath = path.join(dir, 'shakespeare.data.ts');

  const content = await fs.readFile(txtPath, 'utf8');
  const lines = content.split('\n').filter((l) => l.trim().length > 0 && !l.trim().startsWith('#'));

  const cols: [string[], string[], string[]] = [[], [], []];
  for (const line of lines) {
    const parts = line.trim().split(/\s+/);
    if (parts[0]) cols[0].push(parts[0]);
    if (parts[1]) cols[1].push(parts[1]);
    if (parts[2]) cols[2].push(parts[2]);
  }

  const tsCode = `// Auto-generated by gen-data.ts - DO NOT EDIT MANUALLY
export type ShakespeareColumns = [string[], string[], string[]];
export const SHAKESPEARE_COLUMNS: ShakespeareColumns = ${JSON.stringify(cols, null, 2)};
`;
  await fs.writeFile(outPath, tsCode, 'utf8');
  console.log(`Generated ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
