import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

async function main() {
  const dir = path.dirname(fileURLToPath(import.meta.url));
  const txtPath = path.join(dir, 'cat-facts.txt');
  const outPath = path.join(dir, 'cat-facts.data.ts');

  const content = await fs.readFile(txtPath, 'utf8');
  const facts = content
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'));

  const tsCode = `// Auto-generated by gen-data.ts - DO NOT EDIT MANUALLY
export const CAT_FACTS: string[] = ${JSON.stringify(facts, null, 2)};
`;
  await fs.writeFile(outPath, tsCode, 'utf8');
  console.log(`Generated ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
