import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

async function main() {
  const dir = path.dirname(fileURLToPath(import.meta.url));
  const jsonPath = path.join(dir, 'markov.json');
  const outPath = path.join(dir, 'markov.data.ts');

  const content = await fs.readFile(jsonPath, 'utf8');
  const data = JSON.parse(content);

  const tsCode = `// Auto-generated by gen-data.ts - DO NOT EDIT MANUALLY
import type { MarkovData } from './markovword.js';
export const MARKOV_DATA: MarkovData = ${JSON.stringify(data, null, 2)};
`;
  await fs.writeFile(outPath, tsCode, 'utf8');
  console.log(`Generated ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
